version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: repaircontrol_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - repaircontrol_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repaircontrol_app
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      # chave exposta apenas para ambiente de desenvolvimento
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      PORT_SERVER: 3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - repaircontrol_network
    volumes:
      - ./prisma:/app/prisma

volumes:
  postgres_data:
    driver: local

networks:
  repaircontrol_network:
    driver: bridge